
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'DiscoverMelody' do

  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'Masonry', '~> 1.0’
  pod 'MJRefresh', '~> 3.1’
  pod 'JSONModel', '~> 1.7.0’
  pod 'MJExtension', '~> 3.0’

end
